-- =========================================================
-- Moneto — initial database schema (V1)
-- =========================================================

-- ---------- users ----------
CREATE TABLE users (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(255) NOT NULL,
    email                  VARCHAR(255) NOT NULL UNIQUE,
    password               VARCHAR(255) NOT NULL,
    currency               VARCHAR(255) NOT NULL,
    budget_alerts          BOOLEAN,
    recurring_reminders    BOOLEAN,
    month_start            INTEGER,
    is_verified            BOOLEAN,
    verification_token     VARCHAR(255),
    subscription_tier      VARCHAR(255) DEFAULT 'FREE',
    subscription_expires_at DATE,
    role                   VARCHAR(255) DEFAULT 'USER',
    CONSTRAINT users_currency_check CHECK (currency IN ('USD','EUR','GBP','ALL','CAD','CHF','JPY'))
);

-- ---------- categories ----------
CREATE TABLE categories (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255) NOT NULL,
    color    VARCHAR(255),
    icon     VARCHAR(255),
    type     VARCHAR(255) NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT categories_type_check CHECK (type IN ('INCOME','EXPENSE')),
    CONSTRAINT fk_categories_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ---------- transactions ----------
CREATE TABLE transactions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount        NUMERIC(38,2) NOT NULL,
    type          VARCHAR(255) NOT NULL,
    description   VARCHAR(255),
    date          DATE NOT NULL,
    is_recurring  BOOLEAN,
    currency      VARCHAR(255) DEFAULT 'USD',
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    category_id   BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    CONSTRAINT transactions_type_check CHECK (type IN ('INCOME','EXPENSE')),
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- ---------- budgets ----------
CREATE TABLE budgets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount       NUMERIC(38,2) NOT NULL,
    month        INTEGER NOT NULL,
    year         INTEGER NOT NULL,
    category_id  BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    CONSTRAINT fk_budgets_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_budgets_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- ---------- recurring_transactions ----------
CREATE TABLE recurring_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount         NUMERIC(38,2) NOT NULL,
    description    VARCHAR(255),
    frequency      VARCHAR(255) NOT NULL,
    is_active      BOOLEAN,
    next_due_date  DATE NOT NULL,
    type           VARCHAR(255) NOT NULL,
    category_id    BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    CONSTRAINT recurring_frequency_check CHECK (frequency IN ('WEEKLY','MONTHLY','YEARLY')),
    CONSTRAINT recurring_type_check CHECK (type IN ('INCOME','EXPENSE')),
    CONSTRAINT fk_recurring_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_recurring_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- ---------- saving_goals ----------
CREATE TABLE saving_goals (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    target_amount   NUMERIC(38,2) NOT NULL,
    current_amount  NUMERIC(38,2) NOT NULL,
    deadline        DATE NOT NULL,
    status          VARCHAR(255) NOT NULL,
    created_at      TIMESTAMP(6) WITHOUT TIME ZONE,
    user_id         BIGINT NOT NULL,
    CONSTRAINT saving_goals_status_check CHECK (status IN ('IN_PROGRESS','COMPLETED','CANCELLED')),
    CONSTRAINT fk_saving_goals_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ---------- notifications ----------
CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message     VARCHAR(255) NOT NULL,
    is_read     BOOLEAN,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    user_id     BIGINT NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- ---------- alerts ----------
CREATE TABLE alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(255) NOT NULL,
    threshold    NUMERIC(38,2) NOT NULL,
    active       BOOLEAN NOT NULL,
    category_id  BIGINT,
    user_id      BIGINT NOT NULL,
    CONSTRAINT alerts_type_check CHECK (type IN ('DAILY_SPENDING','CATEGORY_SPENDING','MONTHLY_SPENDING','LARGE_TRANSACTION','NEGATIVE_BALANCE')),
    CONSTRAINT fk_alerts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_alerts_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- ---------- audit_logs ----------
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email  VARCHAR(255) NOT NULL,
    action      VARCHAR(255) NOT NULL,
    details     TEXT,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);
