spring.application.name=api
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/moneto
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App
server.port=8080

jwt.secret=your-super-secret-key-that-is-at-least-32-characters
jwt.expiration=86400000

spring.jpa.open-in-view=false

exchange.rate.api.key=${EXCHANGE_API_KEY}
exchange.rate.api.url=https://v6.exchangerate-api.com/v6/

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App base URL for verification links
app.frontend.url=http://localhost:5173